version: '3.8'
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
  api:
    build: ./api
    ports:
      - "8000:8000"
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: example